### ISSUE TITLE
clang-tidy ignores provided `-p` option

### ISSUE THREAD

**Issue by sparfenyuk** [pocc/pre-commit-hooks#5] opened 2019-10-22 09:55 UTC
I am trying to set the directory where compile_commands.json file exists by using -p argument. Clang-tidy hook doesn't use it much. It causes errors while the tool looks for external libraries that are used in the project.
```
fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        types: [c++]
      - id: clang-tidy
        args: [-p=/home/user/projects/myproject/build]
```

**Comment by pocc** [comment] 2019-10-22 21:44
Thank you for reporting this issue. Off the top of my head, I would try using a comma instead of an equals like so:

```
args: [-p, /home/user/projects/myproject/build]
```

Failing that, please provide a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), including the error message.

**Comment by sparfenyuk** [comment] 2019-10-23 06:40
Unfortunately, your suggestion doesn't work for me. Here you can see the minimal reproducible example [mre.zip](https://github.com/pocc/pre-commit-hooks/files/3760562/mre.zip). Conan is required since it puts external libraries into its own path so clang-tidy cannot locate them even if '-p' argument is set in the parameter list. By the way, I want to be able to set a relative path not an absolute one.

**Comment by TheButlah** [comment] 2019-11-15 20:21
I believe I have this same issue

**Comment by TheButlah** [comment] 2019-12-27 20:10
Update: This is till an issue for me. The intended behavior would be to provide the location of the `build` directory relative to the project root. For example, both `[-p, build]`, and `[-p=build]` fail, but if I manually run clang-tidy (not the hook), with `clang-tidy -p=build my_file.cpp`, it works.

I attempted to get around this by using `[-p=$(git rev-parse --show-toplevel)/build]` but that didn't work either, as it doesn't appear as though the shell command was expanded.

**Comment by pocc** [comment] 2019-12-28 04:42
I'm sorry this is still an issue for you. I haven't had time to look at this properly. If you can make a PR, I would be happy to merge.

**Comment by pocc** [comment] 2020-03-22 03:32
@sparfenyuk I've attempted to use your MRE and I see the same 3 errors with the pre-commit config hook as clang-tidy with the same arguments. This is after building it with cmake with the commands provided (on Macos 10.14).

**Note**: I have also made a python branch of this repo (use `rev: python`), which should play nicer with relative file names.

## clang-tidy with arguments

```bash
build rj$ clang-tidy src/* -checks=* -warnings-as-errors=* -p ../build
Error while trying to load a compilation database:
Could not auto-detect compilation database from directory "../build"
No compilation database found in /Users/rj/code/mre/../build or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
Error while processing /Users/rj/code/mre/src/CMakeLists.txt.
396 warnings and 2 errors generated.
Error while processing /Users/rj/code/mre/src/main.cpp.
error: unable to handle compilation, expected exactly one compiler job in '' [clang-diagnostic-error]
/Users/rj/code/mre/src/main.cpp:1:10: error: 'opencv2/opencv.hpp' file not found [clang-diagnostic-error]
#include <opencv2/opencv.hpp>
         ^
/Users/rj/code/mre/src/main.cpp:3:14: error: parameter 'argc' is unused [misc-unused-parameters,-warnings-as-errors]
int main(int argc, char** argv)
             ^~~~
              /*argc*/
/Users/rj/code/mre/src/main.cpp:3:27: error: parameter 'argv' is unused [misc-unused-parameters,-warnings-as-errors]
int main(int argc, char** argv)
                          ^~~~
                           /*argv*/
Suppressed 394 warnings (394 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
2 warnings treated as errors
```

## Same output from clang-tidy hook

```bash
clang-tidy...............................................................Failed
hookid: clang-tidy

Error while processing /Users/rj/code/mre/src/main.cpp.
/Users/rj/code/mre/src/main.cpp:1:10: error: 'opencv2/opencv.hpp' file not found [clang-diagnostic-error]
#include <opencv2/opencv.hpp>
         ^
/Users/rj/code/mre/src/main.cpp:3:14: error: parameter 'argc' is unused [misc-unused-parameters,-warnings-as-errors]
int main(int argc, char** argv)
             ^~~~
              /*argc*/
/Users/rj/code/mre/src/main.cpp:3:27: error: parameter 'argv' is unused [misc-unused-parameters,-warnings-as-errors]
int main(int argc, char** argv)
                          ^~~~
                           /*argv*/
Suppressed 393 warnings (393 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
2 warnings treated as errors
```

**Comment by pocc** [comment] 2020-03-22 03:33
@TheButlah Pre-commit should use project root as cwd.

**Comment by pocc** [comment] 2020-03-26 21:22
Closing as I was adding `--` `-DCMAKEOPTIONS=ON` to suppress no compilation database errors in the bash version, which likely caused this issue. The python version checks for `-p` and `--` options first.

**Closed by pocc** 2020-03-26 21:22 UTC
